a = int("5")
print(a + "5") # line â„– 2 will throw an exception
print(a * "5")
print(ValueError)